routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SolicitudesController;
use  App\Http\Controllers\ServiciosController;
use  App\Http\Controllers\GithubController;
use Laravel\Socialite\Facades\Socialite;

Route::get('/', function () {
    return view('Welcome');
});

Route::get('phpmyinfo', function(){
    phpinfo();
})->name('phpinfo');


Route::get('/servicios/servicio', [ServiciosController::class, 'index'])->name('Servicios');
Route::get('/servicios/editar/{servicio}', [ServiciosController::class, 'edit'])->name('EditS');
Route::get('/servicios/ver/{servicio}', [ServiciosController::class, 'show'])->name('ShowS');
Route::get('/crear-servicio', [ServiciosController::class, 'create'])->name('CreateS');
Route::post('/crear-servicio', [ServiciosController::class, 'store'])->name('storeServicio'); 
Route::put('/servicios/{id}', [ServiciosController::class, 'update'])->name('updateServicio');
Route::delete('/servicios/servicios/{id}', [ServiciosController::class, 'destroy'])->name('eliminarServicio');


Route::get('/solicitudes/Solicitudes', [SolicitudesController::class, 'index'])->name('Solicitudes');
Route::get('/solicitudes/editar/{id}', [SolicitudesController::class, 'edit'])->name('EditSo');
Route::get('/solicitudes/ver/{solicitud}', [SolicitudesController::class, 'show'])->name('ShowSo');
Route::get('/crear-solicitud', [SolicitudesController::class, 'create'])->name('CreateSo');
Route::post('/almacenar-solicitud', [SolicitudesController::class, 'store'])->name('storeSolicitud');
Route::put('/solicitud/{id}', [SolicitudesController::class, 'update'])->name('updateSolicitud');
Route::delete('/solicitudes/solicitudes/{id}', [SolicitudesController::class, 'destroy'])->name('eliminarSolicitud');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::controller(GithubController::class)->group(function(){
    Route::get('auth/github', 'redirectToGithub')->name('auth.github');
    Route::get('auth/github/callback', 'handleGithubCallback');
});

app/Models/Solicitudes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use MongoDB\Laravel\Eloquent\Model as Eloquent;

class Solicitudes extends Eloquent
{
    use HasFactory;

    protected $connection = 'mongodb';
    protected $collection = 'solicitudes';
    protected $primaryKey = '_id';

    protected $fillable = [
        'solicitud',
        'solicitud_id',
        'servicio_id',
        'fecha',
        'hora',
        'usuario_id',
        'fecha_solicitud',
        'numero_niñeras',
        
    ];

    public function usuario() {
        return $this->belongsTo(User::class, 'usuario_id');
    }

    public function servicio(){
        return $this->belongsTo(Servicios::class, 'servicio_id');
    }

    public function getNombreServicioAttribute() {
        return $this->servicio->nombre ?? 'No disponible';
    }
    
    public function getNumeroNinerasAttribute() {
        return $this->numero_niñeras;
    }
    
}

app/Http/Controllers/SolicitudesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Solicitudes;
use App\Models\Servicios;

class SolicitudesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $solicitudes = Solicitudes::all();
        return view('solicitudes/Solicitudes', compact('solicitudes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $servicios = Servicios::all();
        return view('solicitudes/CreateSo', compact('servicios'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // Validar los campos del formulario
        $request->validate([
            'servicio_id' => 'required',
            'fecha' => 'required',
            'hora' => 'required',
            'numero_niñeras' => 'required',
        ]);
    
        // Crear una nueva instancia de Solicitud con los datos del formulario
        $solicitud = new Solicitudes();
        $solicitud->servicio_id = $request->input('servicio_id');
        $solicitud->fecha = $request->input('fecha');
        $solicitud->hora = $request->input('hora');
        $solicitud->numero_niñeras = $request->input('numero_niñeras');
    
        // Guardar la solicitud en la base de datos
        $solicitud->save();
    
        // Redirigir a la página de solicitudes con un mensaje de éxito
        return redirect()->route('Solicitudes')->with('success', 'Solicitud creada exitosamente.');
    }
    

    /**
     * Display the specified resource.
     */
    public function show(Solicitudes $solicitud)
    {
        return view('solicitudes/ShowSo', compact('solicitud'));
    }

    /**
     * Show the form for editing the specified resource.
     */

    public function edit($id)
    {
        $solicitud = Solicitudes::findOrFail($id);
        $servicios = Servicios::all(); // Obtén los servicios que necesites
        return view('solicitudes/EditSo', compact('solicitud', 'servicios'));
    }

public function update(Request $request, $id)
{
    $request->validate([
        'servicio_id' => 'required',
        'fecha' => 'required',
        'hora' => 'required',
        'numero_niñeras' => 'required',
    ]);

    $solicitud = Solicitudes::findOrFail($id);
    $solicitud->update($request->all());

    return redirect()->route('Solicitudes');
}



    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $solicitud = Solicitudes::findOrFail($id);
        $solicitud->delete();

        return redirect()->route('Solicitudes')
            ->with('success', 'Solicitud eliminada exitosamente.');
    }
}

?>

resources/views/solicitudes/CreateSo.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Solicitud</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mt-5 mb-4">Crear Solicitud</h1>

            <form action="{{ route('storeSolicitud') }}" method="POST">

            @csrf

            <div class="form-group">
                <label for="servicio_id">Servicio:</label>
                <select class="form-control" id="servicio_id" name="servicio_id">
                    @foreach ($servicios as $servicio)
                        <option value="{{ $servicio->_id }}">{{ $servicio->nombre }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="fecha">Fecha programada:</label>
                <input type="date" class="form-control" id="fecha" name="fecha">
            </div>

            <div class="form-group">
                <label for="hora">Hora programada:</label>
                <input type="time" class="form-control" id="hora" name="hora">
            </div>

            <div class="form-group">
                <label for="numero_niñeras">Número de Niñeras:</label>
                <select class="form-control" id="numero_niñeras" name="numero_niñeras">
                    @for ($i = 1; $i <= 3; $i++)
                        <option value="{{ $i }}">{{ $i }}</option>
                    @endfor
                </select>
            </div>

            <button type="submit" class="btn btn-sm btn-primary" onclick="return confirm('¿Crear solicitud?')">
                <i class="fas fa-plus"></i> Crear Solicitud
            </button>
            
            <a href="{{ url('solicitudes/Solicitudes') }}" class="btn btn-sm btn-primary">Cancelar</a>
        </form>  
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/solicitudes/EditSo.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Solicitud</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mt-5 mb-4">Editar Solicitud</h1>

 
        <form action="{{ route('updateSolicitud', ['id' => $solicitud->_id]) }}" method="POST">

            @csrf
            @method('PUT')
        
            <div class="form-group">
                <label for="servicio_id">Servicio:</label>
                <select class="form-control" id="servicio_id" name="servicio_id">
                    @foreach ($servicios as $servicio)
                        <option value="{{ $servicio->id }}" {{ $solicitud->servicio_id == $servicio->id ? 'selected' : '' }}>{{ $servicio->nombre }}</option>
                    @endforeach
                </select>
            </div>
        
            <div class="form-group">
                <label for="fecha">Fecha programada:</label>
                <input type="date" class="form-control" id="fecha" name="fecha" value="{{ $solicitud->fecha }}">
            </div>
        
            <div class="form-group">
                <label for="hora">Hora programada:</label>
                <input type="time" class="form-control" id="hora" name="hora" value="{{ $solicitud->hora }}">
            </div>
        
            <div class="form-group">
                <label for="numero_niñeras">Número de Niñeras:</label>
                <select class="form-control" id="numero_niñeras" name="numero_niñeras">
                    @for ($i = 1; $i <= 3; $i++)
                        <option value="{{ $i }}" {{ $solicitud->numero_niñeras == $i ? 'selected' : '' }}>{{ $i }}</option>
                    @endfor
                </select>
            </div>
        
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
            <a href="{{ route('Solicitudes') }}" class="btn btn-primary">Cancelar</a>
        </form>
         
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/solicitudes/Solicitudes.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Solicitud</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mt-5 mb-4">Crear Solicitud</h1>
        <div class="mb-3">
            <a href="{{ route('CreateSo') }}" class="btn btn-primary"><i class="fas fa-plus"></i> Crear Solicitud</a>
        </div> 

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Servicio</th>
                    <th>Usuario</th>
                    <th>Fecha programada</th>
                    <th>Hora programada</th>
                    <th>Número de Niñeras</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($solicitudes as $solicitud)
                    <tr>
                        <td>{{ $solicitud->nombre_servicio }}</td>
                        <td>{{ $solicitud->usuario->nombre ?? 'No disponible' }}</td>
                        <td>{{ $solicitud->fecha}}</td>
                        <td>{{ $solicitud->hora }}</td>
                        <td>{{ $solicitud->numero_nineras }}</td>
                        <td>
                            <a href="{{ route('EditSo', ['id' => $solicitud->_id]) }}" class="btn btn-sm btn-info mr-1"><i class="fas fa-edit"></i></a>


                            <form action="{{ route('eliminarSolicitud', ['id' => $solicitud->_id]) }}" method="POST" style="display: inline;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('¿Estás seguro de que quieres eliminar esta solicitud?')"><i class="fas fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <a href="{{ url('/') }}" class="btn btn-primary">Volver</a>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>